name: Deploy to staging
on:
  push:
    branches:
      -"main"

jobs:
  redeploy_everything:
    name: Deploying everything to staging cluster

    steps:
      -name: SSH into server
      -run: |
       echo ${{secrets.SSH_PRIVATE_KEY}} &> ~/ssh_key 
       ssh -i ~/ssh_key ubuntu@18.196.157.8
       cd BMS/ && git pull
       pnpm install
       pnpm run build
       pm2 restart http-server
       pm2 restart fe-server
       pm2 restart ws-server
       


